export const INSTRUCTOR_REGISTER_SUCCESS = 'INSTRUCTOR_REGISTER_SUCCESS';
export const INSTRUCTOR_REGISTER_ERROR = 'INSTRUCTOR_REGISTER_ERROR';
export const GET_INSTRUCTOR = 'GET_INSTRUCTOR';
export const INSTRUCTOR_LOGIN_SUCCESS = 'INSTRUCTOR_LOGIN_SUCCESS';
export const INSTRUCTOR_LOGIN_ERROR = 'INSTRUCTOR_LOGIN_ERROR';

export const TOGGLE_POPUP = 'TOGGLE_POPUP';

export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_INDIVIDUAL_COURSE = 'GET_INDIVIDUAL_COURSE';
export const GET_ANNOUNCEMENTS = 'GET_ANNOUNCEMENTS';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const DISCARD_FILE = 'DISCARD_FILE';
