export const INSTRUCTOR_REGISTER_SUCCESS = 'INSTRUCTOR_REGISTER_SUCCESS';
export const INSTRUCTOR_REGISTER_ERROR = 'INSTRUCTOR_REGISTER_ERROR';
export const GET_INSTRUCTOR = 'GET_INSTRUCTOR';
export const INSTRUCTOR_LOGIN_SUCCESS = 'INSTRUCTOR_LOGIN_SUCCESS';
export const INSTRUCTOR_LOGIN_ERROR = 'INSTRUCTOR_LOGIN_ERROR';
